#pragma once

#define DIRTY_BIT_ADRESS 0x00

#define DATA_START_ADRESS 0x01
#define DATA_END_ADRESS 0x3C

#define COUNTER_ADRESS 0x3D

#define BATTERY_CALIBRATION_LOW_ADRESS 0x3E
#define BATTERY_CALIBRATION_HIGH_ADRESS 0x3F

#define COUNTER_MAX 0xFFFF